// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWiKHincJ5wHWjTLjE-Fu5DFkk2-u-AiM',
    appId: '1:1005805320895:web:d3b4af0fc367d2fa29240a',
    messagingSenderId: '1005805320895',
    projectId: 'study-app-936b0',
    authDomain: 'study-app-936b0.firebaseapp.com',
    storageBucket: 'study-app-936b0.firebasestorage.app',
    measurementId: 'G-S0KEQYY6Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIhffGmb0ytcFssHGvswbMMg-aAmMkgk',
    appId: '1:1005805320895:android:8ebe74ac1896dec529240a',
    messagingSenderId: '1005805320895',
    projectId: 'study-app-936b0',
    storageBucket: 'study-app-936b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKfbxAL9rdRSq9zqp0N8XavvdzOqq-J9Y',
    appId: '1:1005805320895:ios:a359641a4178009029240a',
    messagingSenderId: '1005805320895',
    projectId: 'study-app-936b0',
    storageBucket: 'study-app-936b0.firebasestorage.app',
    iosBundleId: 'com.example.elearningGroupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKfbxAL9rdRSq9zqp0N8XavvdzOqq-J9Y',
    appId: '1:1005805320895:ios:a359641a4178009029240a',
    messagingSenderId: '1005805320895',
    projectId: 'study-app-936b0',
    storageBucket: 'study-app-936b0.firebasestorage.app',
    iosBundleId: 'com.example.elearningGroupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWiKHincJ5wHWjTLjE-Fu5DFkk2-u-AiM',
    appId: '1:1005805320895:web:a06d47bb07159b4629240a',
    messagingSenderId: '1005805320895',
    projectId: 'study-app-936b0',
    authDomain: 'study-app-936b0.firebaseapp.com',
    storageBucket: 'study-app-936b0.firebasestorage.app',
    measurementId: 'G-M0PFNVH00V',
  );
}
